version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - .:/app/
    ports:
      - '8080:8080'
      - '9229:9229'
    depends_on:
      - db
  db:
    build: ./docker/db
    ports:
      - '5432:5432'
    env_file:
      - ./docker/db/db.env
    volumes:
      - db-data:/var/lib/postgresql/data/
volumes:
  db-data:
